on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: azure/setup-helm@v3
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
        id: install
      - run: helm version
